[package]
edition = "2018"
name = "whitelist-program"
version = "0.1.0"

[dependencies]
solana-program = "1.10.10"
borsh = "0.9.1"
borsh-derive = "0.9.0"
num-derive = "0.3"
num-traits = "0.2"
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "1.10.10"
solana-sdk = "1.10.10"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]